### ISSUE TITLE
ERROR: Procfile does not exist.

### ISSUE THREAD

**Issue by jsquardo** [alpinelab/docker-ruby-dev#7]
I keep getting this error when trying to run docker-compose up. Then it exits with code 1.

**Comment by michaelbaudino** [comment]
Hi @jsquardo and thanks for reporting this :pray: 

This image assumes you are using a `Procfile` to start your app: its default command is `foreman start` as you can see here: https://github.com/alpinelab/docker-ruby-dev/blob/master/Dockerfile#L85

If you are not using a `Procfile` already, you can either:
* create a `Procfile` with something simple like:
    ```
    web: bin/rails server -b 0.0.0.0 -p ${PORT:-5000}
    ```
* change the command used to start your container in your `docker-compose.yml`:
    ```yaml
    version: "3"
    volumes:
      bundle:       { driver: local }
      node_modules: { driver: local }
      config:       { driver: local }
    services:
      app:
        image: alpinelab/ruby-dev
        command: "bin/rails server -b 0.0.0.0 -p 5000"      #  ← this is the new line
        ports: ["5000:5000"]
        volumes:
          - .:/app
          - bundle:/bundle
          - node_modules:/app/node_modules
          - config:/config
    ```

I hope this helps.
